[target.thumbv7m-none-eabi]
runner = "arm-none-eabi-gdb -q -x ../openocd.gdb"
#runner = "cargo embed"
#runner = "probe-run --chip STM32F103C8"

rustflags = [
    "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7m-none-eabi"
